apiVersion: v1
kind: Service
metadata:
  name: irmgard-web-service
  labels:
    app: irmgard-web
spec:
  ports:
    - port: 8080
      name: standard
  selector:
    app: irmgard-web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmgard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irmgard-web
  template:
    metadata:
      labels:
        app: irmgard-web
    spec:
      containers:
        - name: irmgard-container
          image: spam170/irmgard:0.4.0
          ports:
            - containerPort: 8080
              name: standard
          env:
            - name: POSTGRES_HOST
              valueFrom: 
                configMapKeyRef:
                  name: config-htw
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom: 
                configMapKeyRef:
                  name: config-htw
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom: 
                configMapKeyRef:
                  name: config-htw
                  key: POSTGRES_DB
            - name: RABBITMQ_HOST
              valueFrom: 
                configMapKeyRef:
                  name: config-htw
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom: 
                configMapKeyRef:
                  name: config-htw
                  key: RABBITMQ_PORT
            - name: MINIO_ENDPOINT
              valueFrom: 
                configMapKeyRef:
                  name: config-htw
                  key: MINIO_ENDPOINT
            - name: BUCKET_NAME
              valueFrom: 
                configMapKeyRef:
                  name: config-htw
                  key: BUCKET_NAME



            - name: POSTGRES_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: secret-htw
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: secret-htw
                  key: postgres-password
            - name: MINIO_ACCESS_KEY
              valueFrom: 
                secretKeyRef:
                  name: secret-htw
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: secret-htw
                  key: minio-secret-key
            - name: RABBITMQ_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: secret-htw
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: secret-htw
                  key: rabbitmq-pass



